### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [cristian99garcia/laybrinth-activity#1]
🔍

**Comment by quozl** [comment]
Incomplete.  Needs very careful merging.

### git.sugarlabs.org
* last commit is 0acc575 ex pootle in 2014,
* assessment; not needed, is GTK+ 2

### ~ndefilippis
* https://github.com/ndefilippis/Laybrinth-Sugar
* is a clone of git.sugarlabs.org
* is exactly up to date with git.sugarlabs.org
* assessment; not needed

### ~sugarlabs
* https://github.com/sugarlabs/laybrinth-activity
* is not a clone
* is a gtk3 port unreleased as of 18th December 2015
* by Cristian (GCI January 2016)
* assessment; unfinished, adding a thought causes it to vanish, `TypeError: NoneType object has no attribute __getitem__`

### ~Boquete
* https://github.com/Boquete/activity-labyrinth
* is not a clone
* is a gtk3 port unreleased as of 9th January 2016
* by Piotr Antosz (GCI January 2016)
* assessment; unfinished, `SyntaxError: invalid syntax`

### ~Daksh
* https://github.com/Daksh/Labyrinth
* is not a clone
* by Daksh Shah (GCI January 2016)
* assessment; not needed, is GTK+ 2

### Upstream
* https://github.com/labyrinth-team/labyrinth
* is new non-Sugar upstream of some of the code in the activity
* has a GTK+ 3 branch from 2012, and an [issue](https://github.com/labyrinth-team/labyrinth/issues/1) for tracking the port,
* has diverged from the code adopted by Sugar, and will need careful merging,
* assessment; needed.

**Comment by quozl** [comment]
Nothing further needs to be transferred, we're all set.  Repository renamed to fix typo.
